### ISSUE TITLE
Can't compile plugins

### ISSUE THREAD

**Issue by pixelrust** [bontric/Rack-MIDICC-Fork#3]
OS (if applicable): Ubuntu 16.04.3 LTS
Version (or "dev" if compiling from source): Latest commit=fd8d6ab 

I could successfully run this fork version, so I tried to add plugins, but I can't compile them. Maybe I'm doing it wrong? These are the steps I'm following and an excerpt of the error message I get:

- git clone https://github.com/bontric/Rack-MIDICC-Fork.git
- cd Rack-MIDICC-Fork/
- git submodule update --init --recursive
- make dep
- make 
- (make run)
- cd plugins/
- git clone https://github.com/VCVRack/Fundamental.git
- cd Fundamental/
- git submodule update --init --recursive
- make

> g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/VCMixer.cpp.o src/VCMixer.cpp
> src/VCMixer.cpp: In constructor ‘VCMixer::VCMixer()’:
> src/VCMixer.cpp:30:56: error: no matching function for call to ‘rack::Module::Module(VCMixer::ParamIds, VCMixer::InputIds, VCMixer::OutputIds)’
>   VCMixer() : Module(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS) {}
>                                                         ^
> In file included from ../../include/rack.hpp:6:0,
>                  from src/Fundamental.hpp:1,
>                  from src/VCMixer.cpp:1:
> ../../include/engine.hpp:10:8: note: candidate: rack::Module::Module()
>  struct Module {
>         ^
> ../../include/engine.hpp:10:8: note:   candidate expects 0 arguments, 3 provided
> ../../include/engine.hpp:10:8: note: candidate: rack::Module::Module(const rack::Module&)
> ../../include/engine.hpp:10:8: note:   candidate expects 1 argument, 3 provided
> src/VCMixer.cpp: In member function ‘virtual void VCMixer::step()’:
> src/VCMixer.cpp:36:32: error: request for member ‘value’ in ‘((VCMixer*)this)->VCMixer::<anonymous>.rack::Module::inputs.std::vector<_Tp, _Alloc>::operator[]<float*, std::allocator<float*> >(1ul)’, which is of non-class type ‘__gnu_cxx::__alloc_traits<std::allocator<float*> >::value_type {aka float*}’
>   float ch1 = inputs[CH1_INPUT].value * params[CH1_PARAM].value * clampf(inputs[CH1_CV_INPUT].normalize(10.0) / 10.0, 0.0, 1.0);

**Comment by bontric** [comment]
Hey,
the problem is, that the current development version of  [Fundamental](https://github.com/VCVRack/Fundamental) is not compatible with version 0.3.2 which I used as a base for this fork. 

What you need to do, is to use an older version of Fundamental :
```bash
$ cd plugins/Fundamental
$ git reset --hard 0115b024fbcd134cd3481a09adcc9201c0ea5806
$ make clean
$ make
```

**Comment by pixelrust** [comment]
Thanks a lot, that works!

I followed the same approach and managed to get the other plugins running as well.
This worked for me:

Befaco
- git reset --hard 2db46a4a45703ce5674394a60848841ae73fdb2e

ESeries
- git reset --hard 8fa5ddbc4d67214f87cf24d14411e5ae85f95a01

AudibleInstruments
- git reset --hard 248aaafdf1317424cd66569804ed6a411c2984d4

These commits are the latest ones before "Update to new Rack plugin interface" on 26/9.
