### ISSUE TITLE
Static variables in MIDI modules

### ISSUE THREAD

**Issue by DrChrisBoucher** [bontric/Rack-MIDICC-Fork#5]
OS (if applicable): All
Version (or "dev" if compiling from source):

I've noticed some odd use of static variables in some of the core MIDI modules.

It looks like you've already addressed one of them on your `2017-10-bontric-midiCC-fix` branch, so I was wondering if this is the best place to report/discuss them, rather than the main repo?

**Comment by bontric** [comment]
Hey, 
Yeah you are absolutely right. 
I'm still getting used to c++ and for some stupid reason my twisted brain thought static variables are individual for every instance of a class.. :octopus: 

 That is on me, I'll have to fix them asap, caused me a lot of trouble yesterday when I was debugging the midi clock..

**Comment by DrChrisBoucher** [comment]
OK, great :smile:

Happy to review once you're done...

**Comment by bontric** [comment]
> Happy to review once you're done...

I'd really appreciate that. Things have been going quite fast in the past weeks and it's always good to have another eye on the code. 

Btw. if you are interested in helping with development, there is a lot of things! Check the issues and see if there is something you can do. Unfortunately there is no real planning going on right now, but from what I have seen Andrew is really responsive and thankful for all the help he can get.

**Comment by bontric** [comment]
@DrChrisBoucher I fixed the misuse of static variables, feel free to either comment on the pull request or here for anything related to the midi modules.

**Comment by DrChrisBoucher** [comment]
@bontric I made a few comments on the pull request, hope they're OK. Which compiler are you using?

There are a couple more statics I noticed:

In `MIDIClockToCVInterface::step()` I don't think `message` needs to be static, although it's not a problem with the current threading model.

In ` QuadMIDIToCVInterface::processMidi()` I think `gate` should probably be a member variable, otherwise it will be shared between instances.

**Comment by bontric** [comment]
@DrChrisBoucher `gcc 7.2` 

I'll take another look tomorrow, it's getting late.

**Comment by bontric** [comment]
@DrChrisBoucher Thanks

>In MIDIClockToCVInterface::step() I don't think message needs to be static, although it's not a problem with the current threading model.

True, I'll remove it, it's just confusing and based on a misunderstanding anyway.

> In QuadMIDIToCVInterface::processMidi() I think gate should probably be a member variable, otherwise it will be shared between instances.

Doesn't need to be a member, the gates are stored for each `MidiKey` in `activeKeys`. I removed the static however.

**Comment by DrChrisBoucher** [comment]
OK, but I think `gate` should be initialized to false, otherwise it's only set from note on and off messages.

Other than that, looking good 8-)

**Comment by DrChrisBoucher** [comment]
Actually, I'm not sure what it should be initialized to - I don't quite follow how the whole things works, and can test at the moment, but it's currently uninitialized which is certainly wrong.

**Comment by bontric** [comment]
> OK, but I think gate should be initialized to false, otherwise it's only set from note on and off messages.

That's also what it's supposed to be doing :) Look at the switch. Only for note on/off the cases `break` at the end. Otherwise it will `return` since the handling after the switch is related to the polyphonic midi  and modes which is only relevant for note ON/OFF :)

**Comment by DrChrisBoucher** [comment]
Ah, you're right, of course. Never read code before coffee 8-)
